// ---------- Google Analytics ----------
(function () {
  const gtagScript = document.createElement("script");
  gtagScript.async = true;
  gtagScript.src = "https://www.googletagmanager.com/gtag/js?id=G-83SBMLVH1G";
  document.head.appendChild(gtagScript);

  window.dataLayer = window.dataLayer || [];
  function gtag() { dataLayer.push(arguments); }
  gtag("js", new Date());
  gtag("config", "G-83SBMLVH1G");
})();

// ---------- DOM Content Setup ----------
document.addEventListener("DOMContentLoaded", () => {

  // --- Dark Mode Toggle ---
  const container = document.createElement("div");
  container.className = "dark-toggle-container";
  container.innerHTML = `
    <label>
      <input type="checkbox" id="darkModeCheckbox"> Dark Mode
    </label>
  `;
  document.body.prepend(container);

  const darkCheckbox = container.querySelector("#darkModeCheckbox");
  darkCheckbox.addEventListener("change", function () {
    document.body.classList.toggle("dark-mode", this.checked);
  });

  // --- Navigation ---
  const nav = document.createElement("nav");
  nav.style.display = "flex";
  nav.style.flexDirection = "column"; // vertical layout
  nav.style.gap = "0.5rem";
  nav.innerHTML = `
    <a href="/index">Home</a>
    <a href="/blog">Blog</a>
    <a href="/projects">Projects</a>
    <a href="mailto:wesley@wesleymartin.net?subject=From%20Website%20Visitor">
        <i class="fa fa-envelope"></i> Contact
    </a>
  `;
  container.insertAdjacentElement("afterend", nav);

  // --- Wrap content in <main> ---
  const main = document.createElement("main");
  nav.insertAdjacentElement("afterend", main);

  let next = nav.nextSibling;
  const elementsAfterNav = [];
  while (next) {
    const current = next;
    next = next.nextSibling;
    if (current.tagName && current.tagName.toLowerCase() === "footer") break;
    if (current.tagName && current.tagName.toLowerCase() !== "main") {
      elementsAfterNav.push(current);
      current.remove();
    }
  }
  elementsAfterNav.forEach(el => main.appendChild(el));

  // --- Footer with version.txt ---
  const footer = document.createElement("footer");
  document.body.appendChild(footer);

  const versionPath = "version.txt"; // adjust if needed
  fetch(versionPath)
    .then(response => response.text())
    .then(versionText => {
      footer.innerHTML = `
        <p>Copyright 2024–2025 Wesley Martin.</p>
        <p>${versionText}</p>
        <details>
          <summary>Powered by...</summary>
          <p>
            Hosted on <a href="https://pages.github.com" target="_blank">GitHub Pages</a>.<br>
            Domain registered with <a href="https://hover.com" target="_blank">Hover</a>.<br>
            Browser update message by <a href="https://browser-updates.org" target="_blank">Browser-Updates.org</a>.<br>
            Security and email provided by <a href="https://www.cloudflare.com" target="_blank">Cloudflare</a>.<br>
            Forms powered by <a href="https://formspree.io" target="_blank">Formspree</a>.<br>
            HTML mostly generated by <a href="https://chatgpt.com" target="_blank">ChatGPT</a> and 
            <a href="https://gemini.google.com" target="_blank">Gemini</a>, but with significant editing.<br>
            You can view the entire source code for this website on <a href="github.com/wesleyhmartin/wesleyhmartin.github.io">GitHub.</a><br>
            HTML edited with Notepad++ and VS Code.
          </p>
        </details>
        <p>Analytics may be collected.</p>
      `;
    })
    .catch(err => {
      console.error("Failed to load version.txt:", err);
      footer.innerHTML = "<p>Version information not available.</p>";
    });

});

// ---------- Browser Update Notifier ----------
(function () {
  const $buoop = { required: { e: -1, f: -1, o: -1, s: 0, c: -1 }, insecure: true, unsupported: true, api: 2025.10 };
  function $buo_f() {
    const e = document.createElement("script");
    e.src = "https://browser-update.org/update.min.js";
    document.body.appendChild(e);
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", $buo_f, false);
  } else {
    $buo_f();
  }
})();