// ---------- DOM Content Setup ----------
document.addEventListener("DOMContentLoaded", () => {

  // --- Navigation ---
  const nav = document.createElement("nav");
  nav.style.display = "flex";
  nav.style.flexDirection = "column";
  nav.style.gap = "0.5rem";
  nav.innerHTML = `
    <a href="/index">Home</a>
    <a href="/blog">Blog</a>
    <a href="mailto:wesley@wesleymartin.net?subject=From%20Website%20Visitor">Contact</a>
    <a href="/version">Version Information</a>
  `;
  document.body.prepend(nav);

  // --- Wrap content in <main> ---
  const main = document.createElement("main");
  nav.insertAdjacentElement("afterend", main);

  let next = nav.nextSibling;
  const elementsAfterNav = [];
  while (next) {
    const current = next;
    next = next.nextSibling;
    if (current.tagName && current.tagName.toLowerCase() === "footer") break;
    if (current.tagName && current.tagName.toLowerCase() !== "main") {
      elementsAfterNav.push(current);
      current.remove();
    }
  }
  elementsAfterNav.forEach(el => main.appendChild(el));

  // --- Static Footer ---
  const footer = document.createElement("footer");
  footer.innerHTML = `
    <p>Copyright 2024–2025 Wesley Martin.</p>
    <details>
      <summary>Powered by...</summary>
      <p>
        Hosted on <a href="https://pages.github.com" target="_blank">GitHub Pages</a>.<br>
        Domain registered with <a href="https://hover.com" target="_blank">Hover</a>.<br>
        Browser update message by <a href="https://browser-updates.org" target="_blank">Browser-Updates.org</a>.<br>
        Security and email provided by <a href="https://www.cloudflare.com" target="_blank">Cloudflare</a>.<br>
        Forms powered by <a href="https://formspree.io" target="_blank">Formspree</a>.<br>
        HTML formatting (not the text) mostly generated by
        <a href="https://chatgpt.com" target="_blank">ChatGPT</a> and
        <a href="https://gemini.google.com" target="_blank">Gemini</a>, with significant editing.<br>
        Source available on
        <a href="https://github.com/wesleyhmartin/wesleyhmartin.github.io">GitHub</a>.<br>
        Edited with Notepad++ and VS Code.
      </p>
    </details>
  `;
  document.body.appendChild(footer);
});

// ---------- Browser Update Notifier ----------
(function () {
  const $buoop = { required: { e: -1, f: -1, o: -1, s: 0, c: -1 }, insecure: true, unsupported: true, api: 2025.10 };
  function $buo_f() {
    const e = document.createElement("script");
    e.src = "https://browser-update.org/update.min.js";
    document.body.appendChild(e);
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", $buo_f, false);
  } else {
    $buo_f();
  }
})();