// ---------- Google Analytics ----------
(function () {
  const gtagScript = document.createElement("script");
  gtagScript.async = true;
  gtagScript.src = "https://www.googletagmanager.com/gtag/js?id=G-83SBMLVH1G";
  document.head.appendChild(gtagScript);

  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag("js", new Date());
  gtag("config", "G-83SBMLVH1G");
})();

// ---------- Dark Mode, Navigation, Main Wrap, Footer ----------
document.addEventListener("DOMContentLoaded", () => {
  // --- Dark Mode Toggle ---
  const darkContainer = document.createElement("div");
  darkContainer.className = "dark-toggle-container";
  darkContainer.innerHTML = `<label><input type="checkbox" id="darkModeCheckbox"> Dark Mode</label>`;
  document.body.prepend(darkContainer);

  document.querySelector("#darkModeCheckbox").addEventListener("change", function() {
    document.body.classList.toggle("dark-mode", this.checked);
  });

  // --- Navigation ---
  const nav = document.createElement("nav");
  nav.innerHTML = `
    <a href="/index">Home</a><br>
    <a href="/blog"><i class="fa fa-blog"></i> Blog</a><br>
    <a href="/projects"><i class="fa fa-folder-open"></i> Projects</a><br>
    <a href="mailto:wesley@wesleymartin.net?subject=From%20Website%20Visitor">
      <i class="fa fa-envelope"></i> Contact
    </a>
  `;
  darkContainer.insertAdjacentElement("afterend", nav);

  // --- Wrap Content in <main><div class="container"> ---
  const main = document.createElement("main");
  const container = document.createElement("div");
  container.className = "container";

  let next = nav.nextSibling;
  const elementsToMove = [];
  while(next){
    const current = next;
    next = next.nextSibling;
    if(current.tagName && current.tagName.toLowerCase() === "footer") break;
    elementsToMove.push(current);
    current.remove();
  }
  elementsToMove.forEach(el => container.appendChild(el));
  main.appendChild(container);
  nav.insertAdjacentElement("afterend", main);

  // --- Footer with dynamic version ---
  const footer = document.createElement("footer");

  // Fetch version info
  fetch("version.txt")
    .then(response => response.text())
    .then(versionText => {
      footer.innerHTML = `
<form action="https://formspree.io/f/mdkewaja" method="POST">
  <label for="name">Name:</label><br />
  <input type="hidden" id="post_title" name="post_title">
  <input type="text" id="name" name="Display Name:" required />
  <label for="comment">Comment:</label><br />
  <textarea id="comment" name="Comment" rows="4" required></textarea>
  <button type="submit">Submit</button>
  <p>Comments will be reviewed before posting.</p>
</form>
<script>
  document.getElementById("post_title").value = document.title;
</script>

<p>Copyright 2024–2025 Wesley Martin.</p>
<p>${versionText}</p>

<details>
    <summary>Powered by...</summary>
    <p>
        Hosted on <a href="https://pages.github.com" target="_blank">GitHub Pages</a>.<br>
        Domain registered with <a href="https://hover.com" target="_blank">Hover</a>.<br>
        Browser update message by <a href="https://browser-updates.org" target="_blank">Browser-Updates.org</a>.<br>
        Security and email provided by <a href="https://www.cloudflare.com" target="_blank">Cloudflare</a>.<br>
        Forms powered by <a href="https://formspree.io" target="_blank">Formspree</a>.<br>
        HTML mostly generated by <a href="https://chat.openai.com" target="_blank">ChatGPT</a> and 
        <a href="https://gemini.google.com" target="_blank">Gemini</a>, but with significant editing.<br>
        You can view the entire source code for this website on <a href="github.com/wesleyhmartin/wesleyhmartin.github.io>GitHub.</a><br>
        HTML edited with Notepad++ and VS Code.
    </p>
</details>
<p>Analytics may be collected.</p>
      `;
      document.body.appendChild(footer);
    })
    .catch(err => {
      console.error("Failed to load version.txt:", err);
      footer.innerHTML = "<p>Version information not available.</p>";
      document.body.appendChild(footer);
    });
});

// ---------- Browser Update Notifier ----------
(function () {
  const $buoop = { required: { e:-1,f:-1,o:-1,s:0,c:-1 }, insecure:true, unsupported:true, api:2025.10 };
  function $buo_f(){
    const e = document.createElement("script");
    e.src="https://browser-update.org/update.min.js";
    document.body.appendChild(e);
  }
  if(document.readyState === "loading"){
    document.addEventListener("DOMContentLoaded",$buo_f,false);
  } else { $buo_f(); }
})();