// ---------- Navigation, Main Wrap, Footer ----------
document.addEventListener("DOMContentLoaded", () => {
  // --- Navigation ---
  const nav = document.createElement("nav");
  nav.innerHTML = `
    <a href="wesleymartin.net/index">Home</a><br>
    <a href="wesleymartin.net/blog"><i class="fa fa-blog"></i> Blog</a><br>
    <a href="mailto:wesley@wesleymartin.net?subject=From%20Website%20Visitor">Contact</a><br>
    <a href="wesleymartin.net/version">Version Information</a>
  `;
  document.body.prepend(nav);

  // --- Wrap Content in <main><div class="container"> ---
  const main = document.createElement("main");
  const container = document.createElement("div");
  container.className = "container";

  let next = nav.nextSibling;
  const elementsToMove = [];
  while (next) {
    const current = next;
    next = next.nextSibling;
    if (current.tagName && current.tagName.toLowerCase() === "footer") break;
    elementsToMove.push(current);
    current.remove();
  }
  elementsToMove.forEach(el => container.appendChild(el));
  main.appendChild(container);
  nav.insertAdjacentElement("afterend", main);

  // --- Static Footer ---
  const footer = document.createElement("footer");
  footer.innerHTML = `
<form action="https://formspree.io/f/mdkewaja" method="POST">
  <label for="name">Name:</label><br />
  <input type="hidden" id="post_title" name="post_title">
  <input type="text" id="name" name="Display Name:" required /><br>
  <label for="comment">Comment:</label><br />
  <textarea id="comment" name="Comment" rows="4" required></textarea>
  <button type="submit">Submit</button>
  <p>Comments will be reviewed before posting.</p>
</form>

<p>Copyright 2024–2026 Wesley Martin.</p>
<details>
  <summary>Powered by...</summary>
  <p>
    Hosted on <a href="https://pages.github.com" target="_blank">GitHub Pages</a>.<br>
    Domain registered with <a href="https://hover.com" target="_blank">Hover</a>.<br>
    Browser update message by <a href="https://browser-updates.org" target="_blank">Browser-Updates.org</a>.<br>
    Security and email provided by <a href="https://www.cloudflare.com" target="_blank">Cloudflare</a>.<br>
    Forms powered by <a href="https://formspree.io" target="_blank">Formspree</a>.<br>
    HTML formatting (not the text) mostly generated by
    <a href="https://chat.openai.com" target="_blank">ChatGPT</a> and
    <a href="https://gemini.google.com" target="_blank">Gemini</a>, with significant editing.<br>
    Source available on
    <a href="https://github.com/wesleyhmartin/wesleyhmartin.github.io">GitHub</a>.<br>
    Edited with Notepad++ and VS Code.
  </p>
</details>
  `;
  document.body.appendChild(footer);

  // Set post title after footer exists
  const postTitleInput = document.getElementById("post_title");
  if (postTitleInput) {
    postTitleInput.value = document.title;
  }
});

// ---------- Browser Update Notifier ----------
(function () {
  const $buoop = { required: { e:-1,f:-1,o:-1,s:0,c:-1 }, insecure:true, unsupported:true, api:2025.10 };
  function $buo_f(){
    const e = document.createElement("script");
    e.src = "https://browser-update.org/update.min.js";
    document.body.appendChild(e);
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", $buo_f, false);
  } else {
    $buo_f();
  }
})();